name: Matrixed Linux Build
on: [push]
jobs:
  linux:
    strategy:
      matrix:
        os:      [ubuntu-latest]
        target:  [linux]
        variant: [Release, Debug]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }} - ${{ matrix.variant }} on ${{ matrix.os }}
    steps:
      - name: Prep environment
        run: wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - && sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.1.130-bionic.list http://packages.lunarg.com/vulkan/1.1.130/lunarg-vulkan-1.1.130-bionic.list && sudo apt -y update && sudo apt -y install vulkan-sdk libsdl2-dev libglm-dev
      - name: Check out source
        uses: actions/checkout@v1
      - name: Build ${{ matrix.variant }}
        run: chmod 755 VkBuild${{ matrix.variant }}.sh && ./VkBuild${{ matrix.variant }}.sh